#!/usr/bin/env ruby
gem 'test-unit', '1.2.3' if RUBY_VERSION.to_f >= 1.9

puts "Loading Rails environment"
ENV["RAILS_ENV"] ||= 'test'
require File.expand_path('../../config/environment',  __FILE__) unless defined?(RAILS_ROOT)

require 'optparse'
require 'spec/rails/spec_server'
